### ISSUE TITLE
cutoff-solver should error when 3D-haloing doesn't cover full cutoff distance.

### ISSUE THREAD

**Issue by JStewart28** [CUP-ECS/beatnik#67]
This becomes an issue when strong-scaling the problem. When each rank owns a smaller portion of the mesh, the maximum cutoff distance becomes progressively smaller. This effects the accuracy of the model because fewer points are considered neighbors for the zdot solve.

**Comment by patrickb314** [comment]
Not sure this is an issue so much as a limitation of the approach. The real issue is that the code should check for this limitation at startup and fail properly (e.g. by throwing an exception) if the requested cutoff distance is infeasible given the mesh size. Maybe just edit the issue to note this if it's not currently done?

**Comment by patrickb314** [comment]
Fixed by #98
